const permissions = {
  Free: {
    create_trips_max: 10,
    businesses_max: 0,
    storage_max_gb: 0.1,
    docs_max: 10,
    receipts_max: 10,
    accounts_max: 1,
    storage_limit: 0.1,
    buy_more_space: false,
  },
  Personal: {
    create_trips_max: -1,
    businesses_max: 0,
    storage_max_gb: 2,
    docs_max: 100,
    receipts_max: 100,
    accounts_max: 2,
    storage_limit: 2,
    buy_more_space: true,
  },
  Founder: {
    create_trips_max: -1,
    businesses_max: 1,
    storage_max_gb: 10,
    docs_max: 1000,
    receipts_max: 1000,
    accounts_max: 4,
    storage_limit: 10,
    buy_more_space: true,
  },
  Entrepreneur: {
    create_trips_max: -1,
    businesses_max: 3,
    storage_max_gb: 25,
    docs_max: 1000,
    receipts_max: 1000,
    accounts_max: 7,
    storage_limit: 25,
    buy_more_space: true,
  },
  Tycoon: {
    create_trips_max: -1,
    businesses_max: -1,
    storage_max_gb: 100,
    docs_max: -1,
    receipts_max: -1,
    accounts_max: -1,
    storage_limit: 100,
    buy_more_space: true,
  },
  CFO: {
    create_trips_max: -1,
    businesses_max: 2,
    storage_max_gb: 10,
    docs_max: 1000,
    receipts_max: 1000,
    accounts_max: 10,
    view_assigned_customer_data: true,
    storage_limit: 10,
    buy_more_space: true,
  },
  "CFO Management": {
    create_trips_max: -1,
    businesses_max: 2,
    storage_max_gb: 10,
    docs_max: 1000,
    receipts_max: 1000,
    accounts_max: 10,
    view_assigned_customer_data: true,
    assign_permission_levels: true,
    storage_limit: 10,
    buy_more_space: true,
  },
  Admin: {
    create_trips_max: -1,
    businesses_max: -1,
    storage_max_gb: -1,
    docs_max: -1,
    receipts_max: -1,
    accounts_max: -1,
    view_assigned_customer_data: true,
    view_all_customer_data: true,
    assign_permission_levels: true,
    assign_user_info: true,
    assign_clients: true,
    storage_limit: -1,
    buy_more_space: true,
  },
  "Super Admin": {
    create_trips_max: -1,
    businesses_max: -1,
    storage_max_gb: -1,
    docs_max: -1,
    receipts_max: -1,
    accounts_max: -1,
    view_assigned_customer_data: true,
    view_all_customer_data: true,
    assign_permission_levels: true,
    assign_user_info: true,
    assign_clients: true,
    storage_limit: -1,
    buy_more_space: true,
  },
  "Personal+1": {
    create_trips_max: -1,
    businesses_max: 0,
    storage_max_gb: 2,
    docs_max: 100,
    receipts_max: 100,
    accounts_max: 3, // Personal (2) + 1
    storage_limit: 2,
    buy_more_space: true,
  },
  "Founder+1": {
    create_trips_max: -1,
    businesses_max: 1,
    storage_max_gb: 10,
    docs_max: 1000,
    receipts_max: 1000,
    accounts_max: 5, // Founder (4) + 1
    storage_limit: 10,
    buy_more_space: true,
  },
  "Entrepreneur+1": {
    create_trips_max: -1,
    businesses_max: 3,
    storage_max_gb: 25,
    docs_max: 1000,
    receipts_max: 1000,
    accounts_max: 8, // Entrepreneur (7) + 1
    storage_limit: 25,
    buy_more_space: true,
  },
  "Entrepreneur+2": {
    create_trips_max: -1,
    businesses_max: 3,
    storage_max_gb: 25,
    docs_max: 1000,
    receipts_max: 1000,
    accounts_max: 9, // Entrepreneur (7) + 2
    storage_limit: 25,
    buy_more_space: true,
  },
  "Tycoon+100gb": {
    create_trips_max: -1,
    businesses_max: -1,
    storage_max_gb: 200, // Tycoon (100) + 100gb
    docs_max: -1,
    receipts_max: -1,
    accounts_max: -1,
    storage_limit: 200,
    buy_more_space: true,
  },
};

export default permissions;
