const API_KEY = "api-BDACEE253F454000866A0531E2F15859";

export const emailValidation = async (code, email) => {
  try {
    const response = await fetch("https://api.smtp2go.com/v3/email/send", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        api_key: API_KEY,
        to: [email],
        sender: "noreply@zentavos.com",
        subject: "Verification Code",
        html_body: `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html dir="ltr" xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en"><head><meta charset="UTF-8"><meta content="width=device-width, initial-scale=1" name="viewport"><meta name="x-apple-disable-message-reformatting"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta content="telephone=no" name="format-detection"><title>Empty template</title><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,400i,700,700i"><!--<![endif]--><style type="text/css">.rollover:hover .rollover-first { max-height:0px!important; display:none!important;}.rollover:hover .rollover-second { max-height:none!important; display:block!important;}.rollover span { font-size:0px;}u + .body img ~ div div { display:none;}#outlook a { padding:0;}span.MsoHyperlink,span.MsoHyperlinkFollowed { color:inherit; mso-style-priority:99;}a.q { mso-style-priority:100!important; text-decoration:none!important;}a[x-apple-data-detectors],#MessageViewBody a { color:inherit!important; text-decoration:none!important; font-size:inherit!important; font-family:inherit!important; font-weight:inherit!important; line-height:inherit!important;}.g { display:none; float:left; overflow:hidden; width:0; max-height:0; line-height:0; mso-hide:all;}
    @media only screen and (max-width:600px) { *[class="gmail-fix"] { display:none!important } p, a { line-height:150%!important } h1, h1 a { line-height:120%!important } h2, h2 a { line-height:120%!important } h3, h3 a { line-height:120%!important } h4, h4 a { line-height:120%!important } h5, h5 a { line-height:120%!important } h6, h6 a { line-height:120%!important } .bc p { } h1 { font-size:40px!important; text-align:left } h2 { font-size:32px!important; text-align:left } h3 { font-size:28px!important; text-align:left } h4 { font-size:24px!important; text-align:left } h5 { font-size:20px!important; text-align:left } h6 { font-size:16px!important; text-align:left } .bc p, .bc a { font-size:14px!important } .w .rollover:hover .rollover-second, .x .rollover:hover .rollover-second, .y .rollover:hover .rollover-second { display:inline!important } .p, .p .q, .r, .r td, .e { display:inline-block!important }
     .j table, .k table, .l table, .j, .l, .k { width:100%!important; max-width:600px!important } .adapt-img { width:100%!important; height:auto!important } table.d, .esd-block-html table { width:auto!important } .h-auto { height:auto!important } .a .c, .a .c * { font-size:24px!important; line-height:150%!important } .a .b, .a .b * { font-size:14px!important; line-height:150%!important } }@media screen and (max-width:384px) {.mail-message-content { width:414px!important } }</style>
     </head><body class="body" style="width:100%;height:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0"><div dir="ltr" class="es-wrapper-color" lang="en" style="background-color:#F6F6F6"><table width="100%" cellspacing="0" cellpadding="0" class="es-wrapper" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-color:#F6F6F6"><tr><td valign="top" style="padding:0;Margin:0"><table cellspacing="0" cellpadding="0" align="center" class="k" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important;background-color:transparent"> </table>
    <table cellspacing="0" cellpadding="0" align="center" class="j" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important"></table><table cellspacing="0" cellpadding="0" align="center" class="l" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important;background-color:transparent"></table> <table cellspacing="0" cellpadding="0" align="center" class="j" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important"><tr>
    <td bgcolor="transparent" align="center" style="padding:0;Margin:0"><table cellpadding="0" cellspacing="0" bgcolor="#ffffff" align="center" class="bc" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px"><tr>
    <td align="left" background="https://fhlagbv.stripocdn.email/content/guids/CABINET_45cc2e8605954e4bfa4dfd46bbf7a58be9518884b63730d14bbaf918251e95d7/images/emailverificationcode_rg0.png" style="padding:0;Margin:0;padding-top:20px;padding-right:20px;padding-left:20px;background-image:url(https://fhlagbv.stripocdn.email/content/guids/CABINET_45cc2e8605954e4bfa4dfd46bbf7a58be9518884b63730d14bbaf918251e95d7/images/emailverificationcode_rg0.png);background-repeat:no-repeat;background-position:left top"><table width="100%" cellpadding="0" cellspacing="0" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="left" style="padding:0;Margin:0;width:560px"><table width="100%" role="presentation" cellpadding="0" cellspacing="0" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
    <td align="center" style="padding:0;Margin:0;padding-top:10px;padding-bottom:250px;font-size:0"><img width="144" src="https://fhlagbv.stripocdn.email/content/guids/CABINET_45cc2e8605954e4bfa4dfd46bbf7a58be9518884b63730d14bbaf918251e95d7/images/zentavos_logo_v2_white.png" alt="" height="51" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></td> </tr></table></td></tr></table></td></tr></table></td></tr></table> <table cellpadding="0" align="center" cellspacing="0" class="j" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important"><tr>
    <td align="center" bgcolor="transparent" style="padding:0;Margin:0"><table cellpadding="0" cellspacing="0" bgcolor="#ffffff" align="center" class="bc" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px"><tr><td align="left" bgcolor="#D2DBD9" style="padding:0;Margin:0;padding-top:20px;padding-right:20px;padding-left:20px;background-color:#D2DBD9"><table cellspacing="0" width="100%" cellpadding="0" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr><td align="left" style="padding:0;Margin:0;width:560px"><table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;border-radius:2px"><tr>
    <td align="center" bgcolor="#fafafa" class="a" style="padding:0;Margin:0"><p class="c" style="Margin:0;mso-line-height-rule:exactly;font-family:roboto, 'helvetica neue', helvetica, arial, sans-serif;line-height:36px;letter-spacing:0;color:#006747;font-size:24px"><span style="background:transparent">Your verification code</span></p> <p style="Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#6aa84f;font-size:14px"><span style="background:transparent"><br></span></p><p class="b" style="Margin:0;mso-line-height-rule:exactly;font-family:roboto, 'helvetica neue', helvetica, arial, sans-serif;line-height:21px;letter-spacing:0;color:#565861;font-size:14px"><span style="background:transparent">Hi, we hope you're having a great day!<br>To verify your email address, use the verification code:</span></p>
    <p class="b" style="Margin:0;mso-line-height-rule:exactly;font-family:roboto, 'helvetica neue', helvetica, arial, sans-serif;line-height:21px;letter-spacing:0;color:#565861;font-size:14px"><span style="background:transparent"><br></span></p> <p class="b" style="Margin:0;mso-line-height-rule:exactly;font-family:roboto, 'helvetica neue', helvetica, arial, sans-serif;line-height:21px;letter-spacing:0;color:#565861;font-size:14px"><span style="background:transparent"> ${code} </span></p><p class="b" style="Margin:0;mso-line-height-rule:exactly;font-family:roboto, 'helvetica neue', helvetica, arial, sans-serif;line-height:21px;letter-spacing:0;color:#565861;font-size:14px"><span style="background:transparent"><br></span></p>
     <p class="b" style="Margin:0;mso-line-height-rule:exactly;font-family:roboto, 'helvetica neue', helvetica, arial, sans-serif;line-height:21px;letter-spacing:0;color:#565861;font-size:14px"><span style="background:transparent">Enter this code in the app to complete your email verification process. The code is valid for 10 minutes and can only be used once.<br>If you didn’t request this verification, please ignore this email. For any assistance, feel free to contact our support team at info@zentavos.com.<br><br>Make it happen!<br>The Zentavos Team</span></p></td></tr> <tr><td align="center" style="padding:0;Margin:0;padding-top:25px;padding-bottom:25px;font-size:0"><table cellpadding="0" cellspacing="0" class="d r" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tr>
<td valign="top" align="center" style="padding:0;Margin:0;padding-right:10px"><a href="https://www.facebook.com/zentavosinc/" target="_blank" style="mso-line-height-rule:exactly;text-decoration:underline;color:#1376C8;font-size:14px"><img width="20" height="20" title="Facebook" src="https://fhlagbv.stripocdn.email/content/guids/CABINET_45cc2e8605954e4bfa4dfd46bbf7a58be9518884b63730d14bbaf918251e95d7/images/facebook_BCa.png" alt="Fb" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a></td>
 <td align="center" valign="top" style="padding:0;Margin:0;padding-right:10px"><a href="https://www.linkedin.com/company/zentavos/about/" target="_blank" style="mso-line-height-rule:exactly;text-decoration:underline;color:#1376C8;font-size:14px"><img alt="In" width="20" height="20" title="LinkedIn" src="https://fhlagbv.stripocdn.email/content/guids/CABINET_45cc2e8605954e4bfa4dfd46bbf7a58be9518884b63730d14bbaf918251e95d7/images/mdi_linkedin_m49.png" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a></td>
 <td align="center" valign="top" style="padding:0;Margin:0;padding-right:10px"><a target="_blank" href="https://www.instagram.com/zentavosinc/" style="mso-line-height-rule:exactly;text-decoration:underline;color:#1376C8;font-size:14px"><img height="20" title="Instagram" src="https://fhlagbv.stripocdn.email/content/guids/CABINET_45cc2e8605954e4bfa4dfd46bbf7a58be9518884b63730d14bbaf918251e95d7/images/insta.png" alt="Ig" width="20" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a></td>
 <td align="center" valign="top" style="padding:0;Margin:0;padding-right:10px"><a target="_blank" href="https://zentavos.com/privacy-policy" style="mso-line-height-rule:exactly;text-decoration:underline;color:#1376C8;font-size:14px"><img height="20" title="Website" src="https://fhlagbv.stripocdn.email/content/guids/CABINET_45cc2e8605954e4bfa4dfd46bbf7a58be9518884b63730d14bbaf918251e95d7/images/privacypolicy_QP6.png" alt="Website" width="128" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a></td>
 <td align="center" valign="top" style="padding:0;Margin:0;padding-right:10px"><a target="_blank" href="https://zentavos.com/contact-us" style="mso-line-height-rule:exactly;text-decoration:underline;color:#1376C8;font-size:14px"><img height="20" title="Website" src="https://fhlagbv.stripocdn.email/content/guids/CABINET_45cc2e8605954e4bfa4dfd46bbf7a58be9518884b63730d14bbaf918251e95d7/images/help_znV.png" alt="Website" width="43" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></a></td></tr></table></td></tr></table></td></tr></table></td></tr></table></td></tr></table></td></tr></table></div></body></html>`,
      }),
    });
    console.log("Email sent successfully:");
  } catch (error) {
    console.error("Error sending email:", error);
  }
};
