name: zentavos-api-dev

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
  workflow_dispatch:


env:
  DEPLOYMENT_NAME: dev
  BUNDLE_ID: com.zentavos.zentavosdev
  APP_PORT: 3002

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Install OpenVPN
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: openvpn openvpn-systemd-resolved rsync
          version: 1.0
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ztv-build-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ztv-build-
            ztv-
      - name: Install dependencies
        run: npm ci
      - name: Build backend
        run: npm run build
      - name: Replace environment variables
        run: |
          cd dist
          sed -i -e "s|DEPLOYMENT_ENV\=.*|DEPLOYMENT_ENV\=$DEPLOYMENT_NAME|g" scripts/start_server.sh
          sed -i -e "s|MONGODB_URI\=.*|MONGODB_URI\=\'mongodb\:\/\/${{ secrets.MONGODB_URI_DEV }}\'|g" .env.sample
          sed -i -e "s|MONGODB_USER\=.*|MONGODB_USER\=\'${{ secrets.MONGODB_USER_DEV }}\'|g" .env.sample
          sed -i -e "s|MONGODB_PASS\=.*|MONGODB_PASS\=\'${{ secrets.MONGODB_PASS_DEV }}\'|g" .env.sample
          sed -i -e "s|MONGODB_DB\=.*|MONGODB_DB\=\'${{ secrets.MONGODB_DB_DEV }}\'|g" .env.sample
          sed -i -e "s|APP_PORT\=.*|APP_PORT\=$APP_PORT|g" .env.sample
          sed -i -e "s|FIREBASE_SERVICE_ACCOUNT_PATH\=.*|FIREBASE_SERVICE_ACCOUNT_PATH\=./ServiceAccountKey.json|g" .env.sample
          sed -i -e "s|PLAID_CLIENT_ID\=.*|PLAID_CLIENT_ID\=${{ secrets.PLAID_CLIENT_ID_DEV }}|g" .env.sample
          sed -i -e "s|PLAID_SECRET\=.*|PLAID_SECRET\=${{ secrets.PLAID_SECRET_DEV }}|g" .env.sample
          sed -i -e "s|PLAID_WEBHOOK_URL\=.*|PLAID_WEBHOOK_URL\=${{ secrets.PLAID_WEBHOOK_URL_DEV }}|g" .env.sample
          sed -i -e "s|GCP_PROJECT_ID\=.*|GCP_PROJECT_ID\=${{ secrets.GCP_PROJECT_ID }}|g" .env.sample
          sed -i -e "s|GCP_EMAIL\=.*|GCP_EMAIL\=${{ secrets.GCP_EMAIL }}|g" .env.sample
          sed -i -e "s|GCP_PRIVATE_KEY\=.*|GCP_PRIVATE_KEY\=\"${{ secrets.GCP_PRIVATE_KEY }}\"|g" .env.sample
          sed -i -e "s|GCP_KEY_LOCATION\=.*|GCP_KEY_LOCATION\=${{ secrets.GCP_KEY_LOCATION }}|g" .env.sample
          sed -i -e "s|GCP_KEY_RING\=.*|GCP_KEY_RING\=${{ secrets.GCP_KEY_RING }}|g" .env.sample
          sed -i -e "s|GCP_KEY_NAME\=.*|GCP_KEY_NAME\=${{ secrets.GCP_KEY_NAME }}|g" .env.sample
          sed -i -e "s|HASH_SALT\=.*|HASH_SALT\=${{ secrets.HASH_SALT }}|g" .env.sample
          sed -i -e "s|AI_URL\=.*|AI_URL\=${{ secrets.AI_URL }}|g" .env.sample
          sed -i -e "s|AI_MODEL\=.*|AI_MODEL\=${{ vars.AI_MODEL }}|g" .env.sample
          sed -i -e "s|PLAID_REDIRECT_URI\=.*|PLAID_REDIRECT_URI\=${{ secrets.PLAID_REDIRECT_URI_DEV }}|g" .env.sample
          sed -i -e "s|PLAID_REDIRECT_URI_NEW_ACCOUNTS\=.*|PLAID_REDIRECT_URI_NEW_ACCOUNTS\=${{ secrets.PLAID_REDIRECT_URI_NEW_ACCOUNTS_DEV }}|g" .env.sample
          sed -i -e "s|GROQ_AI_MODEL\=.*|GROQ_AI_MODEL\=${{ vars.GROQ_AI_MODEL }}|g" .env.sample
          sed -i -e "s|GROQ_API_KEY\=.*|GROQ_API_KEY\=${{ secrets.GROQ_API_KEY }}|g" .env.sample
          sed -i -e "s|IAP_CERTIFICATE\=.*|IAP_CERTIFICATE\=${{ secrets.IAP_CERTIFICATE }}|g" .env.sample
          sed -i -e "s|STORAGE_SERVICE_ACCOUNT\=.*|STORAGE_SERVICE_ACCOUNT\=${{ secrets.STORAGE_SERVICE_ACCOUNT }}|g" .env.sample
          sed -i -e "s|KMS_SERVICE_ACCOUNT\=.*|KMS_SERVICE_ACCOUNT\=${{ secrets.KMS_SERVICE_ACCOUNT }}|g" .env.sample
          sed -i -e "s|ISSUER_ID\=.*|ISSUER_ID\=${{ secrets.ISSUER_ID }}|g" .env.sample
          sed -i -e "s|KEY_ID\=.*|KEY_ID\=${{ secrets.KEY_ID }}|g" .env.sample
          sed -i -e "s|FIREBASE_SERVICE_ACCOUNT\=.*|FIREBASE_SERVICE_ACCOUNT\=${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}|g" .env.sample
          sed -i -e "s|BUNDLEID\=.*|BUNDLEID\=$BUNDLE_ID|g" .env.sample
          sed -i -e "s|ENVIRONMENT\=.*|ENVIRONMENT\=$DEPLOYMENT_NAME|g" .env.sample
          sed -i -e "/\"type\"\:.*/d" package.json
          cp .env.sample .env
          cd ..
      - name: VPN config
        env:
          OVPN_CONFIG: ${{ secrets.OVPN_CONFIG }}
        run: |
          echo "$OVPN_CONFIG" > client.ovpn
      - name: Connect to VPN
        uses: kota65535/github-openvpn-connect-action@v3.1.0
        with:
          config_file: client.ovpn
          echo_config: false
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
      - name: rsync deployment
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --no-times --omit-dir-times --no-perms --no-owner --no-group --chmod=D755,F664
          path: ./dist/
          remote_path: ${{ vars.DEPLOYMENT_PATH }}
          remote_host: ${{ vars.DEPLOYMENT_HOST_DEV }}
          remote_user: ${{ secrets.DEPLOYMENT_USER_DEV }}
          remote_key: ${{ secrets.DEPLOYMENT_KEY_DEV }}
          remote_port: ${{ secrets.DEPLOYMENT_PORT }}
      - name: SSH config
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOYMENT_KEY_DEV }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem # Write the private key to a file
          chmod 600 private_key.pem # Set the appropriate permissions for the key file
      - name: Restart API service
        run: |
          ssh -i private_key.pem ${{ secrets.DEPLOYMENT_USER_DEV }}@${{ vars.DEPLOYMENT_HOST_DEV }} -p ${{ secrets.DEPLOYMENT_PORT }} -o StrictHostKeyChecking=no <<EOF
            cd ${{ vars.DEPLOYMENT_PATH }}
            chmod +x scripts/start_server.sh
            ./scripts/start_server.sh
          EOF
          rm -f private_key.pem # Remove the private key file after use for security
          rm -f client.ovpn # Remove ovpn file after use for security