name: zentavos-api-dev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build backend
        run: npm run build
      - name: Replace environment variables
        run: |
          sed -i -e "s|MONGODB_URI\=.*|MONGODB_URI\=\'mongodb\:\/\/${{ secrets.MONGODB_URI_QA }}\:27017\'|g" .env.sample
          sed -i -e "s|APP_PORT\=.*|APP_PORT\=3000|g" .env.sample
          cp .env.sample .env
          sed -i -e "/\"type\"\:.*/d" package.json
      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --include ".env"
          path: ./dist/*
          remote_path: ${{ secrets.EC2_DEPLOYMENT_PATH }}/dev
          remote_host: ${{ secrets.EC2_SSH_HOST }}
          remote_user: ${{ secrets.EC2_SSH_USER }}
          remote_key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          rsh: ${{ secrets.EC2_SSH_HOST }} "touch ${{ secrets.EC2_DEPLOYMENT_PATH }}/dev/.env.test"
          #   cd ~/dev
          #   chmod +x ./scripts/start_server.sh
          #   ./scripts/start_server.sh
